

DISC_TYPE_MATRIX = "matrix"
DISC_TYPE_NON_STRUCTURED = "non-structured"

SONNET_DATASET_IDENTIFIER='sonnet'
SONNET_ENDINGS_DATASET_IDENTIFIER = 'sonnet_endings'
LIMERICK_DATASET_IDENTIFIER='limerick'
NUM_LINES_LIMERICK = 5
NUM_LINES_QUATRAIN = 4
NUM_LINES_SONNET = 14

UNKNOWN = '@@UNKNOWN@@'
